# Generated by Django 3.0.3 on 2020-02-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kustom_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
