# Generated by Django 3.0.3 on 2020-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kustom_user', '0003_auto_20200219_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status_of_ticket',
            field=models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], max_length=11),
        ),
    ]
