# Generated by Django 3.0.3 on 2020-02-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kustom_user', '0006_auto_20200220_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status_of_ticket',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], max_length=11),
        ),
    ]
