# Generated by Django 3.0.3 on 2020-02-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kustom_user', '0007_auto_20200220_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='Default body here'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Default text here', max_length=30),
        ),
    ]
